%-*-mode:latex-*-
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% <Copyright = jasone>
% <License>
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Version: <Version>
%
% xep portion of Canonware Software Manual.
%              
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\subsection{xep}
\label{xep}
\index{\classname{xep}{}}
The \classname{xep} class implements exception handling, with support for
\cppdef{xep\_try}, \cppmacro{xep\_catch}{}, and \cppdef{xep\_finally} blocks.
Minimal use must include at least:
\begin{verbatim}
xep_begin();
xep_try {
        /* Code that might throw an exception. */
}
xep_end();
\end{verbatim}

A more complete skeleton looks like:
\begin{verbatim}
xep_begin();
xep_try {
        /* Code that might throw an exception. */
}
xep_catch(SOME_EXCEPTION) {
        /* Handle exception... */
        xep_handled();
}
xep_catch(ANOTHER_EXCEPTION)
xep_mcatch(YET_ANOTHER) {
        /* React to exception, but propagate... */
}
xep_acatch {
        /* Handle all exceptions not explicitly handled above... */
        xep_handled();
}
xep_finally {
        /* Execute after everything else. */
}
xep_end();
\end{verbatim}

Note that there is some serious cpp macro magic behind the \classname{xep}
interface, and as such, if usage deviates significantly from the above
templates, compiler errors may result.

Exception values are of type \ctype{cw\_xepv\_t}.  -1 to -127 are reserved by
\libname{libstash}, and other ranges may be reserved by other libraries.  See
their documentation for details.

An exception is not implicitly handled if an exception handler is executed for
that exception.  Instead, \cfunc{xep\_handled}{} must be manually called to
avoid propagating the exception up the handler chain.

\subsubsection{API}
\begin{description}
\label{xep_begin}
\index{\cppmacro{xep\_begin}{}}
\item[{\cppmacro[void]{xep\_begin}{void}}: ]
	\begin{description}\item[]
	\item[Input(s): ] None.
	\item[Output(s): ] None.
	\item[Exception(s): ] None.
	\item[Description: ]
		Begin an exception handling code block.
	\end{description}
\label{xep_end}
\index{\cppmacro{xep\_end}{}}
\item[{\cppmacro[void]{xep\_end}{void}}: ]
	\begin{description}\item[]
	\item[Input(s): ] None.
	\item[Output(s): ] None.
	\item[Exception(s): ] None.
	\item[Description: ]
		End an exception handling block.
	\end{description}
\label{xep_try}
\index{\cppdef{xep\_try}}
\item[{\cppdef{xep\_try} \dots}: ]
	\begin{description}\item[]
	\item[Input(s): ] None.
	\item[Output(s): ] None.
	\item[Exception(s): ] None.
	\item[Description: ]
		Begin a block of code that is to be executed, with the
		possibility that an exception might be thrown.
	\end{description}
\label{xep_catch}
\index{\cppmacro{xep\_catch}{}}
\item[{\cppmacro{xep\_catch}{cw\_xepv\_t a\_xepv} \dots}: ]
	\begin{description}\item[]
	\item[Input(s): ]
		\begin{description}\item[]
		\item[a\_xepv: ]
			Exception number.
		\end{description}
	\item[Output(s): ] None.
	\item[Exception(s): ] None.
	\item[Description: ]
		Begin a block of code that catches an exception.  The exception
		is not considered handled unless \cfunc{xep\_handled}{} is
		called.
	\end{description}
\label{xep_mcatch}
\index{\cppmacro{xep\_mcatch}{}}
\item[{\cppmacro{xep\_mcatch}{cw\_xepv\_t a\_xepv} \dots}: ]
	\begin{description}\item[]
	\item[Input(s): ]
		\begin{description}\item[]
		\item[a\_xepv: ]
			Exception number.
		\end{description}
	\item[Output(s): ] None.
	\item[Exception(s): ] None.
	\item[Description: ]
		Begin a block of code that catches an exception.  Must
		immediately follow a \cfunc{xep\_catch}{} call.  This interface
		is used for the case where more than one exception type is to be
		handled by the same code block.  The exception is not considered
		handled unless \cfunc{xep\_handled}{} is called.
	\end{description}
\label{xep_acatch}
\index{\cppdef{xep\_acatch}}
\item[{\cppdef{xep\_acatch} \dots}: ]
	\begin{description}\item[]
	\item[Input(s): ] None.
	\item[Output(s): ] None.
	\item[Exception(s): ] None.
	\item[Description: ]
		Begin a block of code that catches all exceptions not explicitly
		caught by \cppmacro{xep\_catch}{} and \cppmacro{xep\_mcatch}{}
		blocks.  There may only be one \cppdef{xep\_acatch} block within
		a try/catch block.  The exception is not considered handled
		unless \cfunc{xep\_handled}{} is called.
	\end{description}
\label{xep_finally}
\index{\cppdef{xep\_finally}}
\item[{\cppdef{xep\_finally} \dots}: ]
	\begin{description}\item[]
	\item[Input(s): ] None.
	\item[Output(s): ] None.
	\item[Exception(s): ] None.
	\item[Description: ]
		Begin a block of code that is executed if no exceptions are
		thrown in the exception handling code block or if an exception
		handler is executed.
	\end{description}
\label{xep_value}
\index{\cfunc{xep\_value}{}}
\item[{\cfunc[cw\_xepv\_t]{xep\_value}{void}}: ]
	\begin{description}\item[]
	\item[Input(s): ] None.
	\item[Output(s): ]
		\begin{description}\item[]
		\item[retval: ]
			Value of the current exception being handled.
		\end{description}
	\item[Exception(s): ] None.
	\item[Description: ]
		Return the value of the current exception being handled.
	\end{description}
\label{xep_throw_e}
\label{xep_throw}
\index{\cfunc{xep\_throw\_e}{}}
\index{\cfunc{xep\_throw}{}}
\item[{\cfunc[void]{xep\_throw\_e}{cw\_xepv\_t a\_xepv, const char *a\_filename,
cw\_uint32\_t a\_line\_num}}: ]
\item[{\cfunc[void]{xep\_throw}{cw\_xepv\_t a\_xepv}}: ]
	\begin{description}\item[]
	\item[Input(s): ]
		\begin{description}\item[]
		\item[a\_xepv: ]
			Exception number to throw.
		\item[a\_filename: ]
			Should be \cppdef{\_\_FILE\_\_}.
		\item[a\_line\_num: ]
			Should be \cppdef{\_\_LINE\_\_}.
		\end{description}
	\item[Output(s): ] None.
	\item[Exception(s): ]
		\begin{description}\item[]
		\item[a\_xepv.]
		\end{description}
	\item[Description: ]
		Throw an exception.
	\end{description}
\label{xep_retry}
\index{\cfunc{xep\_retry}{}}
\item[{\cfunc[void]{xep\_retry}{void}}: ]
	\begin{description}\item[]
	\item[Input(s): ] None.
	\item[Output(s): ] None.
	\item[Exception(s): ] None.
	\item[Description: ]
		Implicitly handle the current exception and retry the
		\cppdef{xep\_try} code block.
	\end{description}
\label{xep_handled}
\index{\cfunc{xep\_handled}{}}
\item[{\cfunc[void]{xep\_handled}{void}}: ]
	\begin{description}\item[]
	\item[Input(s): ] None.
	\item[Output(s): ] None.
	\item[Exception(s): ] None.
	\item[Description: ]
		Mark the current exception as handled.
	\end{description}
\end{description}
